
package com.miw.peliculas.webservices;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IComparadorWS", targetNamespace = "http://webservices.peliculas.miw.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IComparadorWS {


    /**
     * 
     * @return
     *     returns java.util.List<com.miw.peliculas.webservices.Comparacion>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "comparar", targetNamespace = "http://webservices.peliculas.miw.com/", className = "com.miw.peliculas.webservices.Comparar")
    @ResponseWrapper(localName = "compararResponse", targetNamespace = "http://webservices.peliculas.miw.com/", className = "com.miw.peliculas.webservices.CompararResponse")
    @Action(input = "http://webservices.peliculas.miw.com/IComparadorWS/compararRequest", output = "http://webservices.peliculas.miw.com/IComparadorWS/compararResponse")
    public List<Comparacion> comparar();

}
